

const supabaseUrl = 'https://bbqrnohixhctcvxotrph.supabase.co';
const supabaseKey = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJicXJub2hpeGhjdGN2eG90cnBoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MTYyMDIwNTcsImV4cCI6MjAzMTc3ODA1N30.QDJgpzvrjc60h-6N_hOWdk6UbnhLH5H9ab0VU_zEmnc';